### ISSUE TITLE
Select EdgeDriver respectively to installed Edge browser version for LINUX and MACOS

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [SergeyPirogov/webdriver_manager#243]
# Why
Now: webdriver_manager has issues with EdgeDriver because it's not adopted for EdgeDriver release logic for different OS's.
Now: wdm works normal only on WINDOWS.  When you try to run wdm on MACOS and LINUX - it's still trying to download WINDOWS version of EdgeDriver. Without respecting that different OSes have different latest release versions of EdgeDriver.

# What
Here is a logic in published EdgeDriver versions what I have traced looking at EdgeDriver release history on this page: https://msedgedriver.azureedge.net/ 
```python3
if OS == LINUX:
    latest_release_url = LATEST_RELEASE_XX_LINUX
if OS == MAC:
    latest_release_url = LATEST_RELEASE_XX_LINUX
if OS == WIN:
    latest_release_url = LATEST_RELEASE_XX

#  where XX - major Edge Browser Version.
```

Seems reasonable. Need to realize it in WDM and test the changes.

The changes will be only for MAC and LINUX. The Windows logic will be the same like in current  3.5.0 and previous versions of webdriver_manager.

# ToDo
- [x] Realize the logic of selecting edgedriver respectively for different OSes.
- Write tests: 
    - [x] Test With opening EdgeBrowser depends of OS it's running on. 
    - [x] Test With downloading edgedriver and initializing selenium webdriver with binary path for each of OS_TYPE [win32, win64, linux64, mac64]
- Test in CI:
    - [x] CI: add microsoft-edge browser to linux and macos
    - [x] CI: Test edgedriver with microsoft-edge on Linux
    - [x] CI: Test edgedriver with microsoft-edge on MacOS

# P.S.
This feature should resolve edgedriver issues like #242, #162 and others in the nearest future.
